language: php

php:
  - '7.0'

mysql:
  database: dcrphp
  username: root
  password: root
  encoding: utf8

branches:
  only:
    - master

before_install:
  - echo "error_reporting = E_ALL ^ E_NOTICE" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - php dcrphp app:install 127.0.0.1 3306 root root dcrphp
  - php dcrphp app:demo