language: php

php:
  - '7.0'

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
branches:
  only:
    - master

before_install:
  - mysql --version
  - touch env
  - echo "error_reporting = E_ALL ^ E_NOTICE" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - php dcrphp app:install localhost 3306 root root dcrphp
  - php dcrphp app:demo