language: php

php:
  - '7.0'
  #- '7.1'
  #- '7.1'
  #- '7.1'
  #- 'nightly'

services:
  - mysql

branches:
  only:
    - master

before_install:
  - touch env
  - mysql --version
  - echo "error_reporting = E_ALL ^ E_NOTICE" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root -h 127.0.0.1

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - php dcrphp app:install 127.0.0.1 3306 root root dcrphp
  - php dcrphp app:demo
  - cd tests
  - php ../vendor/phpunit/phpunit/phpunit --verbose DcrPHPTest